spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ${APP_NAME}
  data:
    mongodb:
      authentication-database: ${MONGO_AUTH_DB}
      auto-index-creation: ${MONGO_AUTO_INDEX}
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DATABASE}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${PROVIDER_ISSUER_URI}
server:
  port: ${APP_PORT}

springdoc:
  swagger-ui:
    path: /index.html
    enabled: true
  api-docs:
    enabled: true
    path: /v3/api-docs



