apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-customer-deployment
  labels:
    app: ms-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-customer
  template:
    metadata:
      labels:
        app: ms-customer
    spec:
      containers:
        - name: ms-customer
          image: finthos/ms-customer:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ms-customer-config
            - secretRef:
                name: ms-customer-secret
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
