apiVersion: v1
kind: Service
metadata:
  name: ms-customer-service
  labels:
    app: ms-customer
spec:
  selector:
    app: ms-customer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: LoadBalancer